---
title: "R Notebook"
output: html_notebook
---
FEATURE SELECTION 

```{r}
# load the library
library(mlbench)
library(caret)
library(RANN)
```

```{r}
Adult= adult
Adult$capitalgain = NULL
Adult$capitalloss = NULL
Adult$fnlwgt = NULL
Adult$educationnum = NULL
Adult$hoursperweek = NULL
preProcValues = preProcess(Adult, method = c("center","scale"), na.remove = TRUE)
Adult <- predict(preProcValues, Adult)

```

```{r}
dmy <- dummyVars(" ~ .", data = Adult,fullRank = T)
Adult_dummy <- data.frame(predict(dmy, newdata = Adult))

#Converting the dependent variable back to categorical
Adult_dummy$income..50K<-as.factor(Adult_dummy$income..50K)
#deleting neverworked column
Adult_dummy$workclass.Never.worked= NULL
#deleting missing values
Adult_dummy_del = Adult_dummy[which(complete.cases(Adult_dummy)==TRUE),]
```


```{r}

library(FSelector)
```



```{r}

N= nearZeroVar(Adult_dummy_del[,-which(names(Adult_dummy_del)=="income..50K")], saveMetrics = TRUE)
# lets find information gain of attributes
M = information.gain(income..50K~., Adult_dummy_del)
#checking 
rownames(N)==rownames(M)
Z = cbind(N,M)
Z1 = Z[which( Z$attr_importance <= 0.0037 & Z$nzv == TRUE ),] 
name = names(Adult_dummy_del)[!names(Adult_dummy_del) %in% rownames(Z1)]
Adult_dummy_del = Adult_dummy_del[,name]

```




```{r}
# calculate correlation matrix
correlationMatrix = cor(Adult_dummy_del[,-which(names(Adult_dummy_del)=="income..50K")])
# summarize the correlation matrix
print(correlationMatrix)
# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated = findCorrelation(correlationMatrix, cutoff=0.8)
# print indexes of highly correlated attributes
print(highlyCorrelated)
colnames(dummy_del[,highlyCorrelated])
```
```{r}

colnames(Adult_dummy_del)[colnames(Adult_dummy_del)=="income..50K"] = "income"

```

```{r}
set.seed(7)
Set =Adult_dummy_del

# define the control using a random forest selection function
control <- rfeControl(functions=rfFuncs, method="cv", number=3)
# run the RFE algorithm
results <- rfe(Set[,c(1:31,33:39)], Set[,32], sizes=c(1:31,33:39), rfeControl=control)
# summarize the results
print(results)
# list the chosen features
predictors(results)
# plot the results
plot(results, type=c("g", "o"))

```

```{r}
predictorset  = results$control$functions$selectVar(results$variables, 10)

```



