LP1=c( "age",                                     
"workclass.Local.gov",                     
 "workclass.Private"  ,                     
 "workclass.Self.emp.inc"                  ,
 "workclass.Self.emp.not.inc"              ,
 "workclass.State.gov"                     ,
 "workclass.Without.pay"                   ,
 "education.11th"                          ,
 "education.12th"                          ,
 "education.1st.4th"                       ,
 "education.5th.6th"                       ,
 "education.7th.8th"                       ,
 "education.9th"                           ,
 "education.Bachelors"                     ,
 "education.Doctorate"                     ,
 "education.HS.grad"                       ,
 "education.Masters"                       ,
 "education.Preschool"                     ,
 "education.Prof.school"                   ,
 "education.Some.college"                  ,
 "maritalstatus.Married.AF.spouse"         ,
 "maritalstatus.Married.civ.spouse"        ,
 "maritalstatus.Never.married"             ,
 "occupation.Exec.managerial"              ,
 "occupation.Farming.fishing"              ,
 "occupation.Handlers.cleaners"            ,
 "occupation.Machine.op.inspct"            ,
 "occupation.Other.service"                ,
 "occupation.Priv.house.serv"              ,
 "occupation.Prof.specialty"               ,
 "occupation.Protective.serv"              ,
 "occupation.Sales"                        ,
 "occupation.Tech.support"                 ,
 "relationship.Not.in.family"              ,
 "relationship.Other.relative"             ,
 "relationship.Own.child"                  ,
 "relationship.Wife"                       ,
 "race.Black"                              ,
 "race.White"                              ,
 "sex.Male"                                ,
 "nativecountry.Columbia"                  ,
 "nativecountry.Mexico"                    ,
 "nativecountry.South"                     ,
 "nativecountry.Vietnam"                   ,
 "income"                                  ,
 "capitalgain_cat.lowgain"                 ,
 "capitalgain_cat.mediumgain"              ,
 "capitalgain_cat.nogain"                  ,
 "capitalloss_cat.mediumloss"              ,
 "capitalloss_cat.noloss"                  ,
 "hoursperweek_cat.high"                   ,
 "hoursperweek_cat.low"                    ,
 "hoursperweek_cat.veryhigh"               ,
 "hoursperweek_cat.verylow")


LP2=c( "age",                                     
       "workclass.Local.gov",                     
       "workclass.Private"  ,                     
       "workclass.Self.emp.inc"                  ,
       "workclass.Self.emp.not.inc"              ,
       "workclass.State.gov"                     ,
       "workclass.Without.pay"                   ,
       "education.11th"                          ,
       "education.12th"                          ,
       "education.1st.4th"                       ,
       "education.5th.6th"                       ,
       "education.7th.8th"                       ,
       "education.9th"                           ,
       "education.Bachelors"                     ,
       "education.Doctorate"                     ,
       "education.HS.grad"                       ,
       "education.Masters"                       ,
       "education.Preschool"                     ,
       "education.Prof.school"                   ,
       "maritalstatus.Married.AF.spouse"         ,
       "maritalstatus.Married.civ.spouse"        ,
       "maritalstatus.Never.married"             ,
       "occupation.Exec.managerial"              ,
       "occupation.Farming.fishing"              ,
       "occupation.Handlers.cleaners"            ,
       "occupation.Machine.op.inspct"            ,
       "occupation.Other.service"                ,
       "occupation.Priv.house.serv"              ,
       "occupation.Prof.specialty"               ,
       "occupation.Protective.serv"              ,
       "occupation.Sales"                        ,
       "occupation.Tech.support"                 ,
       "relationship.Not.in.family"              ,
       "relationship.Other.relative"             ,
       "relationship.Own.child"                  ,
       "relationship.Wife"                       ,
       "race.Black"                              ,
       "race.White"                              ,
       "sex.Male"                                ,
       "nativecountry.Columbia"                  ,
       "nativecountry.Mexico"                    ,
       "nativecountry.South"                     ,
       "nativecountry.Vietnam"                   ,
       "income"                                  ,
       "capitalgain_cat.mediumgain"              ,
       "capitalgain_cat.nogain"                  ,
       "capitalloss_cat.mediumloss"              ,
       "capitalloss_cat.noloss"                  ,
       "hoursperweek_cat.high"                   ,
       "hoursperweek_cat.low"                    ,
       "hoursperweek_cat.veryhigh"               ,
       "hoursperweek_cat.verylow")

model1 = glm(income~., Adult_dummy, family = "binomial")
model2=glm(income~., Adult_dummy[,LP1], family = "binomial")
model3=glm(income~., Adult_dummy[,LP2], family = "binomial")
RMSE <- sqrt(c(crossprod(model2$residuals))/length(model2$residuals))