--
title: "Untitled"
author: "vidhu"
date: "June 15, 2018"
output: html_document
---
```{r}
predictorset
```

```{r}
colnames(Adult_dummy_del)[colnames(Adult_dummy_del)=="income..50K"] = "income"
levels(Adult_dummy_del$income) =      make.names(levels(factor(Adult_dummy_del$income)))

```
# Control for smote modelling
```{r}
set.seed(400)
ctrl = trainControl(method = "cv", 
                     number = 5, 
                     sampling = "smote",
                     summaryFunction= twoClassSummary, 
                     classProbs=T,
                     savePredictions = T)
```
# kNN -smote
```{r}
grid = expand.grid(k=c(19,31,41,51,100))
kNNFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "knn", use.all = T,trControl = ctrl, metric = "ROC", tuneGrid = grid)
```
```{r}
grid = expand.grid(k=c(100,125,150,200))
kNNFit_tunned = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "knn", use.all = T,trControl = ctrl, metric = "ROC", tuneGrid = grid)
```

```{r}
plot(kNNFit)
varImp(kNNFit)
plot(varImp(kNNFit), main = "variable importance knn")
```

# Random Forest- smote
```{r}
rfFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "rf", trControl = ctrl, metric = "ROC", tuneLength = 5)

```

```{r}
grid = expand.grid(.mtry =2)
rfFit_tuned = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "rf", trControl = ctrl, metric = "ROC",ntree =1000, tuneGrid = grid)

```

```{r}
# Final model 
rfFit
plot(rfFit)
#look at the variable importance and ploting
varImp(rfFit)
plot(varImp(rfFit), main = "variable importance knn")

```

```{r}

svm_linearFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "svmLinear", trControl = ctrl, metric = "ROC", tuneLength = 10)

```

```{r}

svm_RadialFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "svmRadial", trControl = ctrl, metric = "ROC", tuneLength = 10)

```



# Gradient boosting Smote

```{r}

gbmFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "gbm", trControl = ctrl, metric = "ROC", tuneLength = 10)

```

Logistic Regression - smote
```{r}
glmFit = train(Adult_dummy_del[,P1], Adult_dummy_del[,"income"], method = "glm", trControl = ctrl, metric = "ROC", family="binomial")

```

```{r}
#Confusion Matrix
confusionMatrix(predict(kNNFit),Adult_dummy_del[,"income"])
confusionMatrix(predict(rfFit),Adult_dummy_del[,"income"])
confusionMatrix(predict(gbmFit),Adult_dummy_del[,"income"])
confusionMatrix(predict(svm_linearFit),Adult_dummy_del[,"income"])
# Plotting ROC
library(pROC)
roc1 = roc(response = as.numeric(Adult_dummy_del$income), predictor = as.numeric(predict(kNNFit)))
plot(roc1, col = "blue")
roc2 = roc(response = as.numeric(Adult_dummy_del$income), predictor = as.numeric(predict(rfFit)))
plot(roc2, add = T, col= "red")
roc3 = roc(response = as.numeric(Adult_dummy_del$income), predictor = as.numeric(predict(gbmFit)))
plot(roc3, add = T, col = "black")
roc4 = roc(response = as.numeric(Adult_dummy_del$income), predictor = as.numeric(predict(svm_linearFit)))
plot(roc4, add = T, col = "green")
roc5 = roc(response = as.numeric(Adult_dummy_del$income), predictor = as.numeric(predict(glmFit)))
plot(roc5, add = T, col = "yellow")

# Fmeasure 
F_meas(predict(knnfFit),Adult_dummy_del[,"income"],relevant ="X0"  )
F_meas(predict(rfFit),Adult_dummy_del[,"income"],relevant ="X0"  )
F_meas(predict(gbmFit),Adult_dummy_del[,"income"],relevant ="X0"  )
F_meas(predict(svmFit),Adult_dummy_del[,"income"],relevant ="X0"  )
```
# Run all models with imputing missing values.
```{r}
Adult_dummy_imputed = knnImputation(Adult_dummy)
colnames(Adult_dummy_imputed)[colnames(Adult_dummy_imputed)=="income..50K"] = "income"
levels(Adult_dummy_imputed$income) =      make.names(levels(factor(Adult_dummy_imputed$income)))
```

```{r}
grid = expand.grid(k=c(19,31,41,51,100))
kNNFit = train(Adult_dummy_imputed[,P1], Adult_dummy_imputed[,"income"], method = "knn", use.all = T,trControl = ctrl, metric = "ROC", tuneGrid = grid)
```



```{r}
rfFit_imputed = train(Adult_dummy_imputed[,P1], Adult_dummy_imputed[,"income"], method = "rf", trControl = ctrl, metric = "ROC", tuneLength = 10)

```

```{r}
#Predictors for top layer models 
top_models = data.frame(predict(kNNFit),predict(rfFit),predict(svm_linearFit), predict(gbmFit), predict(glmFit)) 

#GBM as top layer model 
ensemble_gbm = train(predictors_top,Adult_dummy_del$income,method='gbm',trControl= ctrl,tuneLength=3)
```